Lemoncode/quickmock

src/pods/canvas/canvas.pod.tsx
src/pods/canvas/use-selection.hook.ts

Added feature: Canvas clear selection
Here, I improved the code in the "use-selection.hook.ts" hook to deselect shapes previously selected from the transformerRef when the user clicks on the canvas.
Regards!
Closes #17

#17 canvas clear selection added

---

src/core/providers/canvas/zindex.util.spec.ts
src/core/providers/canvas/zindex.util.ts

Tested corner cases: 
- Correct performance of each function
- The element is already in the target position
- The shape id is not found
- The list of shapes is empty
closes #65

#65 unit tests to zindex

---

src/common/components/inline-edit/inline-edit.tsx

- Enhanced useEffect to handle Enter key press
- Submit text and exit edit mode when Enter key is pressed
- Maintain proper cleanup of event listeners
closed #95

Add keydown listener for Enter key to submit text

---

src/core/providers/canvas/canvas.model.ts
src/core/providers/canvas/canvas.provider.tsx
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/use-monitor-shape.hook.ts
src/pods/canvas/use-transform.hook.ts

Update provider funcions

---

src/layout/main.layout.module.css
src/pods/component-gallery/component-gallery.pod.tsx
src/pods/component-gallery/component.pod.module.css
src/pods/container-gallery/container-gallery.pod.tsx
src/pods/container-gallery/container.pod.module.css
src/pods/footer/components/index.ts
src/pods/footer/components/zoom-in-button.tsx
src/pods/footer/components/zoom-out-button.tsx
src/pods/footer/footer.pod.module.css
src/pods/footer/footer.pod.tsx
src/pods/toolbar/components/toolbar-button/toolbar-button.tsx
src/pods/toolbar/components/zoom-in-button/zoom-in-button.tsx
src/pods/toolbar/components/zoom-out-component/zoom-out-button.tsx
src/pods/toolbar/toolbar.pod.module.css
src/pods/toolbar/toolbar.pod.tsx
src/scenes/main.module.css
src/scenes/main.scene.tsx

It has 3 different commits, the first one modify the initial grid in case @deletidev wants to take a look at it. There was a className in component-gallery.pod.tsx that wasn't being applied, now the app preserves the 100vh without scrolls.
closes #96

Feature#96 add footer with zoom info

---

src/common/components/inline-edit/inline-edit.tsx

add select all text as well

---

src/common/components/icons/delete-icon.component.tsx
src/core/providers/canvas/canvas.business.spec.ts
src/core/providers/canvas/canvas.business.ts
src/core/providers/canvas/canvas.model.ts
src/core/providers/canvas/canvas.provider.tsx
src/pods/toolbar/components/delete-button/delete-button.tsx
src/pods/toolbar/components/delete-button/index.ts
src/pods/toolbar/toolbar.pod.tsx

Feature/#79 Added delete shape via toolbar

---

src/common/utils/shapes/shape-restrictions.spec.ts
src/common/utils/shapes/shape-restrictions.ts

Cases:
- Width 0, Width 1,
- Width in bounds
- Width out of bounds max
- Width out of bouns min
- Height out of bounds max
- Height out of bounds min
- Width and Height out of bound max
- Witdth and Height out of bouns min
- All bound -1
closed #45

Add unit tests for fitSizeToShapeSizeRestrictions function

---

src/pods/canvas/shape-renderer/simple-container/tablet.render.tsx

Add missing props in renderTablet as with:
`      onDragEnd={handleDragEnd(shape.id)}
onTransform={handleTransform}
onTransformEnd={handleTransform}`
issue #36

reopened-issue/#36-add missing props in renderTablet

---

public/shapes/line.svg
src/common/components/front-basic-sapes/index.ts
src/common/components/front-basic-sapes/line-basic-shape.tsx
src/core/model/index.ts
src/pods/basic-shapes-gallery/basic-gallery-data/index.ts
src/pods/canvas/canvas.model.ts
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/index.ts
src/pods/canvas/shape-renderer/simple-basic-shapes/line.renderer.tsx
src/pods/canvas/use-transform.hook.ts

Created Line Basic Shape. Closes #150 
I had to do some fixing, the transformer works badly for very small elements. I have created a 10 px transparent rectangle containing the line so it can work.
@brauliodiez I have a question here, should we change the drag "points" of the transformer for certain figures? For example, a line could only be extended to the sides, but not from the corners. 
Do you think it could be solved directly from the Hook of the transformer? I've made some approximations and it seems to work, but I'd have to get some info from the provider, I don't know if you want me to take a look at it. 
````
//useEffect
if (transformerRef.current) {
if (selectedShapeType === 'line') {
transformerRef.current.enabledAnchors(['middle-left', 'middle-right']);
} else { …
```

#150 line shape created

---

src/pods/canvas/use-monitor.business.spec.ts

- Adding test case to validate that the function returns the correct offset when the X coordinate is greater than the calculated offset. 
- Adding test case to ensure the function returns 0 when the X coordinate minus the calculated offset is negative or zero.
- Mocked getDefaultSizeFromShape to provide specific widths for different shape types.
Closes #156

Add unit tests for calculateShapeOffsetToXDropCoordinate function

---

src/common/components/front-basic-sapes/postit-basic-shape.tsx
src/common/components/front-basic-sapes/rectangle-basic-shape.tsx
src/common/components/front-components/button-shape.tsx
src/common/components/front-components/combobox-shape.tsx
src/common/components/front-components/datepickerinput-shape.tsx
src/common/components/front-components/input-shape.tsx
src/common/components/front-components/listbox/listbox-shape.tsx
src/common/components/front-components/textarea-shape.tsx
src/common/components/front-components/timepickerinput-shape.tsx
src/common/components/front-rich-components/horizontal-menu.tsx
src/common/components/front-rich-components/modal/modal.tsx
src/common/components/front-rich-components/vertical-menu/vertical-menu.tsx
src/core/model/index.ts
src/pods/canvas/canvas.model.ts
src/pods/properties/components/border-radius/border-radius.component.tsx
src/pods/properties/components/border-radius/border-radius.module.css
src/pods/properties/components/border-radius/index.ts
src/pods/properties/components/index.ts
src/pods/properties/properties.pod.tsx

feat: Add border-radius property and implement selection buttons
- Added `borderRadius` property to component props.
- Updated the interface and relevant components to handle the new `borderRadius` property.
- Implemented the `borderRadius` property in relevant components, including `InputShape`.
- Created three buttons in the `BorderRadius` component to select between different border radius options: Sharp, Rounded, and Smooth.
- Adjusted styles to align buttons to the right of the container and enhance visual presentation.
Closes #223

Added `borderRadius` property

---

src/pods/canvas/canvas.model.ts
src/pods/properties/components/border-radius/border-radius.component.tsx

use the default border in border selection

---

index.html

The size of the video on youtube is squarer than expected and breaks the design in many ways, so for the moment I have left it in 16/9 for the video to be seen but it shows black stripes, for it to look good it is in 13.5/9. I will look at how to fix the landing design but it will take more time and I might change the design completely.
Closes #371

landing video

---

src/common/components/front-rich-components/accordion/accordion.business.spec.ts
src/common/components/front-rich-components/accordion/accordion.business.ts

- Add tests for the default sections when input is empty
- Add test for handling a single section in the text
- Add test for two sections, where one starts with [*] (marked as selected)
- Add test for multiple sections without any marked [*]
- Ensure only the first section marked with [*] is selected when multiple are marked
- Handle edge cases: special characters
Closes #169

add unit test for mapTextToSections function

---

src/common/components/mock-components/front-text-components/paragraph-text-shape.tsx

now the text takes up all the available space.
Closes #427

#427 fix bug on paragraph component

---

src/common/components/mock-components/front-text-components/smalltext-shape.tsx

I've changed min-width to a minimum of 40, to take into account cases like single letters or numbers in menus or lists:
closes #447

adjust small text component min width

---

src/pods/thumb-pages/thumb-pages.module.css

Add flex-direction: column to thumb-pages module CSS
Very simple fix, to change the flex-direction as a column.

Closes #491

---

src/pods/properties/components/stroke-style/stroke.style.component.tsx

Keep in mind that in Basic shapes, both the Horizontal Line and the Vertical Line, if we set the stroke style to none it will no longer be seen although the component is still there.
Closes #492

Add option to stroke style none

---

src/common/components/mock-components/front-components/shape.const.ts
src/common/components/mock-components/front-text-components/heading1-text-shape.tsx
src/common/components/mock-components/front-text-components/heading2-text-shape.tsx
src/common/components/mock-components/front-text-components/heading3-text-shape.tsx
src/common/components/mock-components/front-text-components/link-text-shape.tsx
src/common/components/mock-components/front-text-components/normaltext-shape.tsx
src/common/components/mock-components/front-text-components/paragraph-text-shape.tsx
src/common/components/mock-components/front-text-components/smalltext-shape.tsx
src/common/components/shapes/use-shape-props.hook.ts
src/core/local-disk/shapes-to-document.mapper.ts
src/core/model/index.ts
src/pods/canvas/model/shape-other-props.utils.ts
src/pods/properties/components/text-alignment/index.ts
src/pods/properties/components/text-alignment/text-alignment.module.css
src/pods/properties/components/text-alignment/text-alignment.tsx
src/pods/properties/properties.pod.tsx

- Implements buttons to align text to the left, center, and right.
- Integrates custom SVG icons to visually represent each alignment option.
- Adds dynamic classes to highlight the active button based on the selected alignment.
- Enhances modularity with encapsulated styles using CSS Modules.
- Allows alignment state management through props and callbacks.
This functionality improves the user experience by providing intuitive controls for text alignment.
Closes #529

add text alignment functionality to the TextAlignment component

---

e2e/inline-edit/rename-thumb-page.spec.ts

add functionality to rename thumbnail pages via direct edit and context menu
- Implemented e2e test for renaming a thumbnail page.
- Verified renaming using direct double-click edit.
- Added context menu interaction to rename pages.
- Ensured renamed pages are correctly updated and visible in the UI.
Closes #550

add rename thumb page

---

e2e/inline-edit/visible-thumb-page.spec.ts

- Ensures the thumb page is visible in the DOM
- Confirms the chevron (SVG element within the thumb page) is rendered and visible
- Validates the visibility of the "add new page" button with the appropriate accessible label
Closes #543

feature/#543 verify visibility of thumb page, chevron, and add new page button

---

src/common/components/mock-components/front-containers/modal-dialog-shape.tsx
src/pods/canvas/model/inline-editable.model.ts
src/pods/canvas/shape-renderer/simple-container/modal-dialog-container.renderer.tsx

**Steps:**
- Added missing properties to the render and child components.
- Added missing types and default values.
**Editable title**

Feature/#601 Add editable title to modal dialog

---

src/common/utils/shapes/on-click-keyboard.ts
vite.config.ts

Closes #668 
- Added support for `Shift + Click` to enable multi-selection.  
- Verified that `Ctrl + Click` and normal `Click` still work as expected.  
- Tested in the browser, and everything is working correctly. 🚀  
Here’s a visual confirmation of the feature in action:

feat: add Shift + Click support for multi-selection #668

---

src/pods/canvas/canvas.pod.module.css

Remove the relative position of the canvas because the calculations in the right shape menu are broken.
Closes #718

Remove the relative position of the canvas 

---

public/low-wireframes/lowHorizontalLine.svg
public/low-wireframes/verticalLineLow.svg
src/common/components/mock-components/front-low-wireframes-components/index.ts
src/common/components/mock-components/front-low-wireframes-components/vertical-line-low-shape.tsx
src/core/model/index.ts
src/pods/canvas/model/shape-other-props.utils.ts
src/pods/canvas/model/shape-size.mapper.ts
src/pods/canvas/model/transformer.model.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-low-wireframes-components/index.ts
src/pods/canvas/shape-renderer/simple-low-wireframes-components/low-vertical-line.renderer.tsx
src/pods/galleries/low-wireframe-gallery/low-wireframe-gallery-data/index.ts

implemented low vertical line shape component

---

public/low-wireframes/horizontalLineLow.svg
src/common/components/mock-components/front-low-wireframes-components/horizontal-line-low-shape.tsx
src/common/components/mock-components/front-low-wireframes-components/index.ts
src/core/model/index.ts
src/pods/canvas/model/shape-other-props.utils.ts
src/pods/canvas/model/shape-size.mapper.ts
src/pods/canvas/model/transformer.model.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-low-wireframes-components/index.ts
src/pods/canvas/shape-renderer/simple-low-wireframes-components/low-horizontal-line.renderer.tsx
src/pods/galleries/low-wireframe-gallery/low-wireframe-gallery-data/index.ts

implemented low horizontal shape component

---

e2e/thumb-pages/change-thumb-selected-add-component.spec.ts

test: verify shapes drop in correct thumb page and remain isolated across page switches

---

e2e/thumb-pages/delete-button-disabled-when-only-one-thumb-page.spec.ts

test: verify delete thumb page button is disabled when only one page remains
