Lemoncode/quickmock

src/common/components/gallery/components/item-component.module.css
src/common/components/gallery/gallery-component.module.css
src/layout/main.layout.module.css
src/main.css
src/main.tsx
src/normalize.css
src/pods/canvas/canvas.pod.module.css
src/pods/canvas/canvas.pod.tsx
src/pods/component-gallery/component-gallery.pod.tsx
src/pods/component-gallery/component.pod.module.css
src/pods/container-gallery/container.pod.module.css

Added normalize.css and main theme

---

public/widgets/toggleswitch.svg
src/common/components/front-components/index.ts
src/common/components/front-components/toggleswitch-shape.tsx
src/core/model/index.ts
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/canvas.util.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-component/index.ts
src/pods/canvas/shape-renderer/simple-component/toggleswitch.renderer.tsx
src/pods/component-gallery/component-gallery-data/index.ts

ToggleSwitch Shape implemented.
Also: 
- Added Barrel in src/common/components/front-components/index.ts
- Edited Types to prevent key React errors in src/pods/component-gallery/component-gallery-data/index.ts 
Closes #31

#31 toggleswitch implemented

---

public/containers/browser.svg
public/containers/mobile.svg
public/containers/tablet.svg
src/pods/container-gallery/container-gallery-data/index.ts
src/pods/container-gallery/container-gallery.pod.tsx
src/pods/container-gallery/container.pod.module.css

Feature/#48 create container gallery 

---

public/widgets/checkbox.svg
src/common/components/front-components/checkbox-shape.tsx
src/common/components/front-components/index.ts
src/core/model/index.ts
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/canvas.util.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-component/checkbox.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/index.ts
src/pods/component-gallery/component-gallery-data/index.ts

- SVG checkbox file created and inside paste the SVG
- Checkbox Shape Component created
- Uncomment checkbox in the core/model/index.ts
- Checkbox render component created
- Add  the function of render the checkbox in pods/canvas/shape-render/index.tsx
Close #21

feature/#21 Create Checkbox Konva Component 

---

public/widgets/datepicker.svg
src/common/components/front-components/datepickerinput-shape.tsx
src/common/components/front-components/index.ts
src/core/model/index.ts
src/pods/canvas/canvas.model.ts
src/pods/canvas/canvas.util.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-component/datepickerinput.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/index.ts
src/pods/component-gallery/component-gallery-data/index.ts

* Create datepicker components
* Added svg datepicker
* implement the component to change the size 
* Add a solid white background to the input inner content
Closes #54

Feature/#54 Datepicker as konva component

---

src/common/components/front-components/index.ts
src/common/components/front-containers/browserwindow-shape.tsx
src/common/components/front-containers/index.ts
src/core/model/index.ts
src/pods/canvas/canvas.model.ts
src/pods/canvas/canvas.util.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-container/browserwindow.render.tsx
src/pods/canvas/shape-renderer/simple-container/index.ts

* Create browser component and render
*  Implement the component to change the size
Closes #35

Feature/#35 Create a browser container as Konva Component

---

src/common/components/front-components/button-shape.tsx
src/common/components/front-components/combobox-shape.tsx
src/common/components/front-components/input-shape.tsx
src/common/components/front-components/textarea-shape.tsx

#61#62-issue adjustment of shapes for text centring and ellipsis

---

.github/workflows/ci.yml
package.json

feature/#76 Aded setup CI

---

public/widgets/label.svg
src/common/components/front-components/label-shape.tsx
src/core/model/index.ts
src/pods/canvas/canvas.util.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/model.ts
src/pods/canvas/shape-renderer/simple-component/index.ts
src/pods/canvas/shape-renderer/simple-component/label.renderer.tsx
src/pods/component-gallery/component-gallery-data/index.ts

Text label 

---

src/common/components/inline-edit/inline-edit.tsx

#93 add focus at start of editing

---

public/widgets/radiobutton.svg
src/common/components/front-components/index.ts
src/common/components/front-components/radiobutton-shape.tsx
src/core/model/index.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-component/index.ts
src/pods/canvas/shape-renderer/simple-component/radiobutton.renderer.tsx
src/pods/component-gallery/component-gallery-data/index.ts

Added Radio Button with ability to check and uncheck.
Closes #22

Feature: added radio button to component gallery.

---

src/common/components/front-components/button-shape.tsx
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/simple-component/button.renderer.tsx

Make the button editable inline edition

---

src/core/providers/canvas/use-selection.hook.ts
src/pods/canvas/canvas.pod.tsx

Bug fix/#130 Fixed hide transformer when deleting element

---

src/common/components/inline-edit/inline-edit.tsx
src/common/helpers/platform.helpers.ts
src/core/providers/canvas/canvas.model.ts
src/pods/toolbar/components/delete-button/delete-button.tsx
src/pods/toolbar/components/toolbar-button/toolbar-button.tsx
src/pods/toolbar/shortcut/shortcut.const.ts
src/pods/toolbar/shortcut/shortcut.hook.tsx
src/pods/toolbar/shortcut/shortcut.model.ts

- Implemented useShortcut hook for managing keyboard shortcuts.
- Updated ToolbarButton component to use the useShortcut hook.
- Configured DeleteButton to use new shortcut functionality with the 'Delete' key.
Closes #134

Add keyboard shortcut for delete-button

---

public/rich-components/videoPlayer.svg
src/common/components/front-rich-components/index.ts
src/common/components/front-rich-components/video-player.tsx
src/core/model/index.ts
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/rectangle.rerender.tsx
src/pods/canvas/shape-renderer/simple-rich-components/index.ts
src/pods/canvas/shape-renderer/simple-rich-components/video-player.renderer.tsx
src/pods/canvas/use-monitor-shape.hook.ts
src/pods/canvas/use-monitor.business.ts
src/pods/index.ts
src/pods/rich-components-gallery/basic-shapes-gallery.pod.tsx
src/pods/rich-components-gallery/rich-components-gallery-data/index.ts
src/scenes/main.scene.tsx

Adding also first rich-component: videoPlayer
Closes #152

Adding Rich Components gallery

---

src/common/components/inline-edit/inline-edit.tsx
src/common/components/inline-edit/inline-edit.utils.spec.ts
src/common/components/inline-edit/inline-edit.utils.ts

create inline edit functions
close #90

Optimize inline edit calculate X Y and widht height functions

---

src/common/components/icons/delete-icon.component.tsx
src/pods/toolbar/components/about-button/about-button.tsx
src/pods/toolbar/components/delete-button/delete-button.tsx
src/pods/toolbar/components/export-button/export-button.tsx
src/pods/toolbar/components/new-button/new-button.tsx
src/pods/toolbar/components/open-button/open-button.tsx
src/pods/toolbar/components/redo-button/redo-button.tsx
src/pods/toolbar/components/save-button/save-button.tsx
src/pods/toolbar/components/toolbar-button/index.ts
src/pods/toolbar/components/toolbar-button/toolbar-button.tsx
src/pods/toolbar/components/undo-button/undo-button.tsx
src/pods/toolbar/components/zoom-in-button/zoom-in-button.tsx
src/pods/toolbar/components/zoom-out-component/zoom-out-button.tsx
src/pods/toolbar/shortcut/shortcut.hook.tsx
src/pods/toolbar/toolbar.pod.module.css
src/pods/toolbar/toolbar.pod.tsx

Updating buttons with new configuration and splitting buttons into actions

---

src/common/components/front-components/radiobutton-shape.tsx
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/simple-component/radiobutton.renderer.tsx

Feature/#128 Made radio button editable

---

src/common/components/front-components/checkbox-shape.tsx
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/simple-component/checkbox.renderer.tsx

Feature/#129 Made checkbox editable

---

src/pods/properties/components/color-picker/color-picker.component.module.css
src/pods/properties/components/color-picker/color-picker.component.tsx
src/pods/properties/properties.pod.tsx

#191 added consistent style to props gallery

---

src/common/components/gallery/gallery-component.module.css
src/common/components/gallery/gallery-component.tsx
src/core/model/index.ts

Feature/#198 Added title to each shapes in the gallery

---

src/common/components/front-rich-components/pie-chart.tsx

feature/#205 Fix scaleY on pie-chart component

---

public/shapes/triangle.svg
src/core/model/index.ts

* The trinagle property was missing from the types.
* Change the svg to make it fit better and be centered, in the basic shapes component.

Add property triangle in type

---

src/common/components/front-basic-sapes/circle-basic-shape.tsx
src/common/components/front-basic-sapes/diamond-shape.tsx
src/common/components/front-basic-sapes/line-basic-shape.tsx
src/common/components/front-basic-sapes/postit-basic-shape.tsx
src/common/components/front-basic-sapes/rectangle-basic-shape.tsx
src/common/components/front-basic-sapes/star-shape.tsx
src/common/components/front-basic-sapes/triangle-basic-shape.tsx
src/common/components/front-components/button-shape.tsx
src/common/components/front-components/combobox-shape.tsx
src/common/components/front-components/datepickerinput-shape.tsx
src/common/components/front-components/listbox/listbox-shape.tsx
src/common/components/front-components/textarea-shape.tsx
src/common/components/front-components/timepickerinput-shape.tsx
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/simple-basic-shapes/circle.renderer.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/diamond.renderer.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/line.renderer.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/postit.rerender.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/rectangle.rerender.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/star.renderer.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/triangle.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/combobox.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/datepickerinput.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/listbox.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/textarea.renderer.tsx
src/pods/canvas/shape-renderer/simple-component/timepickerinput.renderer.tsx

add stroke and fill

---

public/shapes/rectangle.svg
src/common/components/front-basic-sapes/postit-basic-shape.tsx
src/common/components/front-components/button-shape.tsx
src/common/components/front-components/checkbox-shape.tsx
src/common/components/front-components/combobox-shape.tsx
src/common/components/front-components/input-shape.tsx
src/common/components/front-components/label-shape.tsx
src/common/components/front-components/radiobutton-shape.tsx
src/common/components/front-components/textarea-shape.tsx
src/common/components/front-rich-components/breadcrumb/breadcrumb.tsx
src/common/components/front-rich-components/horizontal-menu.tsx
src/common/components/front-text-components/heading1-text-shape.tsx
src/common/components/front-text-components/heading2-text-shape.tsx
src/common/components/front-text-components/heading3-text-shape.tsx
src/common/components/front-text-components/normaltext-shape.tsx
src/common/components/front-text-components/paragraph-text-shape.tsx
src/common/components/front-text-components/smalltext-shape.tsx
src/pods/canvas/canvas.model.ts
src/pods/canvas/shape-renderer/simple-component/label.renderer.tsx
src/pods/canvas/shape-renderer/simple-rich-components/breadcrumb.renderer.tsx
src/pods/canvas/shape-renderer/simple-rich-components/horizontal-menu.renderer.tsx

Split switch-cases for different components based on their use of stroke, background, checked and textColor.
Also centered rectangle's thumbnail of the svg
Closes #193

TextColor Property

---

src/common/components/front-rich-components/table/table-col-width.utils.spec.ts
src/common/components/front-rich-components/table/table-col-width.utils.ts

#253 unit tests added to table-col-width

---

src/common/components/gallery/components/item-component.module.css
src/common/components/gallery/components/item-component.tsx
src/common/components/gallery/gallery-component.module.css
src/common/components/gallery/gallery-component.tsx
src/main.css

organized gallery

---

src/core/providers/canvas/use-selection.hook.ts

fix delete

---

src/core/providers/canvas/canvas.model.ts
src/core/providers/canvas/use-selection.hook.ts
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/use-keyboard-displacement.tsx

#299 add custom hook for keyboard displacements

---

src/pods/canvas/use-multiple-selection-shape.hook.tsx
src/pods/canvas/use-multiple-selection.business.ts

fix applied

---

src/pods/toolbar/shortcut/shortcut.hook.tsx

fix shortcut

---

src/common/components/gallery/components/item-component.module.css
src/common/components/gallery/components/item-component.tsx
src/main.css
src/scenes/main.module.css

Gallery hover

---

LICENSE
README.md

Pending on adding the youtube video

first update Readme

---

public/widgets/checkbox.svg
src/common/components/front-components/checkbox-shape.tsx

Updated checkbox styles

---

public/widgets/combobox.svg
src/common/components/front-components/combobox-shape.tsx
src/common/components/front-components/shape.const.ts

updated combobox styles

---

public/widgets/radiobutton.svg
src/common/components/front-components/radiobutton-shape.tsx

Updated radio button styles

---

src/common/components/inline-edit/components/image-upload.widget.module.css

changed image button colors

---

src/pods/context-menu/components/commands.component.tsx
src/pods/context-menu/use-context-menu.hook.tsx

#355 only zindex avaliable on context menu

---

src/common/components/inline-edit/hooks/use-submit-cancel-hook.ts
src/common/components/inline-edit/inline-edit.tsx
src/core/providers/canvas/canvas.model.ts
src/core/providers/canvas/canvas.provider.tsx
src/pods/canvas/canvas.pod.tsx
src/pods/canvas/use-keyboard-displacement.tsx
src/pods/toolbar/shortcut/shortcut.const.ts
src/pods/toolbar/shortcut/shortcut.hook.tsx

#385 promoted isInlineEditing to provider

---

e2e/inline-edit/simple-inline-edit.spec.ts
package.json
playwright.config.ts
vite.config.ts

#402 [QA] Edit inline shape e2e test

---

e2e/inline-edit/simple-inline-edit.spec.ts

#403 [QA] Edit inline shape plus delete key

---

src/common/components/mock-components/front-rich-components/table/table-col-width.utils.spec.ts
src/common/components/mock-components/front-rich-components/table/table.tsx
src/common/components/mock-components/front-rich-components/table/table.utils.ts

Now if a row has less items than max columns "commas" are added when render. 
Closes #434

#424 table bug fix

---

src/common/components/mock-components/front-components/button-shape.tsx
src/pods/canvas/model/transformer.model.ts

#376 now we can edit button height

---

e2e/inline-edit/simple-inline-edit.spec.ts

#436 case added - Esc cancel inline edit

---

src/pods/properties/components/font-style/font-style.module.css
src/pods/properties/components/font-style/font-style.tsx
src/pods/properties/components/font-variant/font-variant.module.css
src/pods/properties/components/font-variant/font-variant.tsx
src/pods/properties/components/text-decoration/text-decoration.module.css
src/pods/properties/components/text-decoration/text-decoration.tsx

Feature/#457 fix checkbox with underline, bold and italic properties to text components

---

src/pods/canvas/use-transform.hook.ts

#448 remove rotate hanger from transformer

---

src/common/components/mock-components/front-text-components/heading1-text-shape.tsx
src/common/components/mock-components/front-text-components/heading2-text-shape.tsx
src/common/components/mock-components/front-text-components/heading3-text-shape.tsx
src/common/components/mock-components/front-text-components/normaltext-shape.tsx

adjust h1,h2,h3 and normal-text min-width value

---

src/common/components/mock-components/front-basic-shapes/vertical-line-basic-shape.tsx

cleanup remove TODO

---

src/core/local-disk/shapes-to-document.mapper.ts
src/core/local-disk/shapes-to.document.mapper.spec.ts
src/core/local-disk/use-local-disk.hook.ts

- Updated Version on Save File to 0.2.
- Created new function to handle V0.1 Saves into one page.
Closes #502

#503 - BugFix

---

src/pods/thumb-pages/components/thumb-page.module.css
src/pods/thumb-pages/components/thumb-page.tsx
src/pods/thumb-pages/thumb-pages.module.css
src/pods/thumb-pages/thumb-pages.pod.tsx

add style thumbnail rectangle and highlight selected

---

src/common/components/mock-components/front-components/shape.const.ts
src/pods/canvas/model/shape-other-props.utils.ts

work in progress

---

src/common/components/mock-components/front-components/button-shape.tsx

fixed vertical text in to button component

---

src/pods/properties/components/image-black-and-white/image-black-and-white-selector.component.tsx
src/pods/toolbar/components/export-button/export-button.tsx

#565 bw filters fixed when export

---

src/pods/toolbar/components/export-button/export-button.tsx
src/pods/toolbar/components/export-button/export-button.utils.ts

#583-add-filename-to-export-image and refactor

---

src/common/components/mock-components/front-basic-shapes/horizontal-line-basic-shape.tsx
src/common/components/mock-components/front-basic-shapes/vertical-line-basic-shape.tsx

adjusted min line width height

---

src/common/components/mock-components/front-basic-shapes/large-arrow-shape.tsx

big arrow min width adjustment

---

src/pods/properties/components/icon-selector/modal/components/icon-list.component.module.css
src/pods/properties/components/icon-selector/modal/icon-modal.module.css

- Changed Icon Wrapper to use media queries to adapt to the resolution and add a scroll
- Udated icon-modal to have a maximum height based on the viewport to remove the scroll on the modal.

Closes #504

---

src/common/components/mock-components/front-components/datepickerinput-shape.tsx

Closes #608 
Bug fixed, duplicate text.

- Removed Extra text.

---

src/common/components/mock-components/front-components/listbox/listbox-shape.tsx

#633 fine tunning disabled listbox

---

src/common/components/tooltip/tooltip.component.module.css
src/common/components/tooltip/tooltip.component.tsx
src/pods/toolbar/components/toolbar-button/toolbar-button.tsx

Still no closes
Actually working with Ctrl for all systems, should we implement cmd for Mac ? 
Only a few icons have shortcuts, its time to implement all? 
*Added a 1s delay to show tooltips for not being too intrusive.

#635-add-tooltips-to-toolbar

---

index.html

Not available on mobile

---

src/common/components/mock-components/front-rich-components/table/table.utils.ts

Table fields allow escaping ","

---

src/common/components/mock-components/front-components/input-shape.tsx
src/common/components/shapes/use-shape-props.hook.ts
src/core/local-disk/shapes-to-document.mapper.ts
src/core/model/index.ts
src/pods/canvas/model/shape-other-props.utils.ts
src/pods/properties/properties.pod.tsx

added isPassword property to input shape

---

public/low-wireframes/imagePlaceholder.svg
src/common/components/mock-components/front-low-wireframes-components/image-placeholder-shape.tsx
src/common/components/mock-components/front-low-wireframes-components/index.ts
src/core/model/index.ts
src/pods/canvas/model/shape-size.mapper.ts
src/pods/canvas/model/transformer.model.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-basic-shapes/index.ts
src/pods/canvas/shape-renderer/simple-low-wireframes-components/image-placeholder.renderer.tsx
src/pods/canvas/shape-renderer/simple-low-wireframes-components/index.ts
src/pods/canvas/shape-renderer/simple-text-components/index.ts
src/pods/galleries/index.ts
src/pods/galleries/low-wireframe-gallery/low-wireframe-gallery-data/index.ts
src/pods/galleries/low-wireframe-gallery/low-wireframe-gallery.pod.tsx
src/scenes/main.scene.tsx

Closes #728 
and also closes #729  - I did the first low wireframe (image placeholder) as an entry point for the rest.

#728 create low wireframe section

---

e2e/rectangle-shape.spec.ts
public/low-wireframes/rectangleLow.svg
src/common/components/mock-components/front-low-wireframes-components/index.ts
src/common/components/mock-components/front-low-wireframes-components/rectangle-low-shape.tsx
src/core/model/index.ts
src/pods/canvas/model/shape-other-props.utils.ts
src/pods/canvas/model/shape-size.mapper.ts
src/pods/canvas/shape-renderer/index.tsx
src/pods/canvas/shape-renderer/simple-low-wireframes-components/index.ts
src/pods/canvas/shape-renderer/simple-low-wireframes-components/rectangle-low.renderer.tsx
src/pods/galleries/low-wireframe-gallery/low-wireframe-gallery-data/index.ts

Feature/#731 low wireframes   create thick rectangle placeholder

---

src/common/components/mock-components/front-text-components/paragraph-text-shape.tsx

Update paragraph minWidth to allow smaller values
